/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AdminAuditLogsRouteImport } from './routes/_admin/audit-logs'
import { Route as AdminHolidaysRouteImport } from './routes/_admin/holidays'
import { Route as AdminSemestersRouteImport } from './routes/_admin/semesters'
import { Route as AdminTimetableRouteImport } from './routes/_admin/timetable'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as ParentMessagesRouteImport } from './routes/_parent/messages'
import { Route as ParentParentRouteImport } from './routes/_parent/parent'
import { Route as PortalAchievementsRouteImport } from './routes/_portal/achievements'
import { Route as PortalAnalyticsRouteImport } from './routes/_portal/analytics'
import { Route as PortalAnnouncementsRouteImport } from './routes/_portal/announcements'
import { Route as PortalAssistantRouteImport } from './routes/_portal/assistant'
import { Route as PortalDevicesRouteImport } from './routes/_portal/devices'
import { Route as PortalLeaderboardRouteImport } from './routes/_portal/leaderboard'
import { Route as PortalLeaveRouteImport } from './routes/_portal/leave'
import { Route as PortalSettingsRouteImport } from './routes/_portal/settings'
import { Route as StudentEligibilityRouteImport } from './routes/_student/eligibility'
import { Route as StudentScanRouteImport } from './routes/_student/scan'
import { Route as StudentStudentRouteImport } from './routes/_student/student'
import { Route as TeacherApprovalsRouteImport } from './routes/_teacher/approvals'
import { Route as TeacherMaterialsRouteImport } from './routes/_teacher/materials'
import { Route as TeacherTeacherRouteImport } from './routes/_teacher/teacher'

const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/_admin/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/_admin/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHolidaysRoute = AdminHolidaysRouteImport.update({
  id: '/_admin/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSemestersRoute = AdminSemestersRouteImport.update({
  id: '/_admin/semesters',
  path: '/semesters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/_admin/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/_auth/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/_auth/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/_parent/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentParentRoute = ParentParentRouteImport.update({
  id: '/_parent/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAchievementsRoute = PortalAchievementsRouteImport.update({
  id: '/_portal/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAnalyticsRoute = PortalAnalyticsRouteImport.update({
  id: '/_portal/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAnnouncementsRoute = PortalAnnouncementsRouteImport.update({
  id: '/_portal/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAssistantRoute = PortalAssistantRouteImport.update({
  id: '/_portal/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDevicesRoute = PortalDevicesRouteImport.update({
  id: '/_portal/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLeaderboardRoute = PortalLeaderboardRouteImport.update({
  id: '/_portal/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLeaveRoute = PortalLeaveRouteImport.update({
  id: '/_portal/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/_portal/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEligibilityRoute = StudentEligibilityRouteImport.update({
  id: '/_student/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScanRoute = StudentScanRouteImport.update({
  id: '/_student/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentRoute = StudentStudentRouteImport.update({
  id: '/_student/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherApprovalsRoute = TeacherApprovalsRouteImport.update({
  id: '/_teacher/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/_teacher/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTeacherRoute = TeacherTeacherRouteImport.update({
  id: '/_teacher/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminAdminRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/holidays': typeof AdminHolidaysRoute
  '/semesters': typeof AdminSemestersRoute
  '/timetable': typeof AdminTimetableRoute
  '/otp': typeof AuthOtpRoute
  '/messages': typeof ParentMessagesRoute
  '/parent': typeof ParentParentRoute
  '/achievements': typeof PortalAchievementsRoute
  '/analytics': typeof PortalAnalyticsRoute
  '/announcements': typeof PortalAnnouncementsRoute
  '/assistant': typeof PortalAssistantRoute
  '/devices': typeof PortalDevicesRoute
  '/leaderboard': typeof PortalLeaderboardRoute
  '/leave': typeof PortalLeaveRoute
  '/settings': typeof PortalSettingsRoute
  '/eligibility': typeof StudentEligibilityRoute
  '/scan': typeof StudentScanRoute
  '/student': typeof StudentStudentRoute
  '/approvals': typeof TeacherApprovalsRoute
  '/materials': typeof TeacherMaterialsRoute
  '/teacher': typeof TeacherTeacherRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminAdminRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/holidays': typeof AdminHolidaysRoute
  '/semesters': typeof AdminSemestersRoute
  '/timetable': typeof AdminTimetableRoute
  '/otp': typeof AuthOtpRoute
  '/messages': typeof ParentMessagesRoute
  '/parent': typeof ParentParentRoute
  '/achievements': typeof PortalAchievementsRoute
  '/analytics': typeof PortalAnalyticsRoute
  '/announcements': typeof PortalAnnouncementsRoute
  '/assistant': typeof PortalAssistantRoute
  '/devices': typeof PortalDevicesRoute
  '/leaderboard': typeof PortalLeaderboardRoute
  '/leave': typeof PortalLeaveRoute
  '/settings': typeof PortalSettingsRoute
  '/eligibility': typeof StudentEligibilityRoute
  '/scan': typeof StudentScanRoute
  '/student': typeof StudentStudentRoute
  '/approvals': typeof TeacherApprovalsRoute
  '/materials': typeof TeacherMaterialsRoute
  '/teacher': typeof TeacherTeacherRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin/admin': typeof AdminAdminRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/holidays': typeof AdminHolidaysRoute
  '/_admin/semesters': typeof AdminSemestersRoute
  '/_admin/timetable': typeof AdminTimetableRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_parent/messages': typeof ParentMessagesRoute
  '/_parent/parent': typeof ParentParentRoute
  '/_portal/achievements': typeof PortalAchievementsRoute
  '/_portal/analytics': typeof PortalAnalyticsRoute
  '/_portal/announcements': typeof PortalAnnouncementsRoute
  '/_portal/assistant': typeof PortalAssistantRoute
  '/_portal/devices': typeof PortalDevicesRoute
  '/_portal/leaderboard': typeof PortalLeaderboardRoute
  '/_portal/leave': typeof PortalLeaveRoute
  '/_portal/settings': typeof PortalSettingsRoute
  '/_student/eligibility': typeof StudentEligibilityRoute
  '/_student/scan': typeof StudentScanRoute
  '/_student/student': typeof StudentStudentRoute
  '/_teacher/approvals': typeof TeacherApprovalsRoute
  '/_teacher/materials': typeof TeacherMaterialsRoute
  '/_teacher/teacher': typeof TeacherTeacherRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/audit-logs'
    | '/holidays'
    | '/semesters'
    | '/timetable'
    | '/otp'
    | '/messages'
    | '/parent'
    | '/achievements'
    | '/analytics'
    | '/announcements'
    | '/assistant'
    | '/devices'
    | '/leaderboard'
    | '/leave'
    | '/settings'
    | '/eligibility'
    | '/scan'
    | '/student'
    | '/approvals'
    | '/materials'
    | '/teacher'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/audit-logs'
    | '/holidays'
    | '/semesters'
    | '/timetable'
    | '/otp'
    | '/messages'
    | '/parent'
    | '/achievements'
    | '/analytics'
    | '/announcements'
    | '/assistant'
    | '/devices'
    | '/leaderboard'
    | '/leave'
    | '/settings'
    | '/eligibility'
    | '/scan'
    | '/student'
    | '/approvals'
    | '/materials'
    | '/teacher'
    | '/'
  id:
    | '__root__'
    | '/_admin/admin'
    | '/_admin/audit-logs'
    | '/_admin/holidays'
    | '/_admin/semesters'
    | '/_admin/timetable'
    | '/_auth/otp'
    | '/_parent/messages'
    | '/_parent/parent'
    | '/_portal/achievements'
    | '/_portal/analytics'
    | '/_portal/announcements'
    | '/_portal/assistant'
    | '/_portal/devices'
    | '/_portal/leaderboard'
    | '/_portal/leave'
    | '/_portal/settings'
    | '/_student/eligibility'
    | '/_student/scan'
    | '/_student/student'
    | '/_teacher/approvals'
    | '/_teacher/materials'
    | '/_teacher/teacher'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminAdminRoute: typeof AdminAdminRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminHolidaysRoute: typeof AdminHolidaysRoute
  AdminSemestersRoute: typeof AdminSemestersRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AuthOtpRoute: typeof AuthOtpRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentParentRoute: typeof ParentParentRoute
  PortalAchievementsRoute: typeof PortalAchievementsRoute
  PortalAnalyticsRoute: typeof PortalAnalyticsRoute
  PortalAnnouncementsRoute: typeof PortalAnnouncementsRoute
  PortalAssistantRoute: typeof PortalAssistantRoute
  PortalDevicesRoute: typeof PortalDevicesRoute
  PortalLeaderboardRoute: typeof PortalLeaderboardRoute
  PortalLeaveRoute: typeof PortalLeaveRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  StudentEligibilityRoute: typeof StudentEligibilityRoute
  StudentScanRoute: typeof StudentScanRoute
  StudentStudentRoute: typeof StudentStudentRoute
  TeacherApprovalsRoute: typeof TeacherApprovalsRoute
  TeacherMaterialsRoute: typeof TeacherMaterialsRoute
  TeacherTeacherRoute: typeof TeacherTeacherRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/holidays': {
      id: '/_admin/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AdminHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/semesters': {
      id: '/_admin/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof AdminSemestersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/timetable': {
      id: '/_admin/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_parent/messages': {
      id: '/_parent/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_parent/parent': {
      id: '/_parent/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/achievements': {
      id: '/_portal/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof PortalAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/analytics': {
      id: '/_portal/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof PortalAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/announcements': {
      id: '/_portal/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof PortalAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/assistant': {
      id: '/_portal/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof PortalAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/devices': {
      id: '/_portal/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof PortalDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/leaderboard': {
      id: '/_portal/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof PortalLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/leave': {
      id: '/_portal/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof PortalLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/settings': {
      id: '/_portal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/eligibility': {
      id: '/_student/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof StudentEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/scan': {
      id: '/_student/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof StudentScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/student': {
      id: '/_student/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_teacher/approvals': {
      id: '/_teacher/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof TeacherApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_teacher/materials': {
      id: '/_teacher/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof TeacherMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_teacher/teacher': {
      id: '/_teacher/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminAdminRoute: AdminAdminRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminHolidaysRoute: AdminHolidaysRoute,
  AdminSemestersRoute: AdminSemestersRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AuthOtpRoute: AuthOtpRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentParentRoute: ParentParentRoute,
  PortalAchievementsRoute: PortalAchievementsRoute,
  PortalAnalyticsRoute: PortalAnalyticsRoute,
  PortalAnnouncementsRoute: PortalAnnouncementsRoute,
  PortalAssistantRoute: PortalAssistantRoute,
  PortalDevicesRoute: PortalDevicesRoute,
  PortalLeaderboardRoute: PortalLeaderboardRoute,
  PortalLeaveRoute: PortalLeaveRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  StudentEligibilityRoute: StudentEligibilityRoute,
  StudentScanRoute: StudentScanRoute,
  StudentStudentRoute: StudentStudentRoute,
  TeacherApprovalsRoute: TeacherApprovalsRoute,
  TeacherMaterialsRoute: TeacherMaterialsRoute,
  TeacherTeacherRoute: TeacherTeacherRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
